# Generated by Django 3.0.4 on 2020-05-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
