# Generated by Django 3.0.4 on 2020-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200523_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amount',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
