# Generated by Django 3.0.4 on 2020-06-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='ordernumber',
            field=models.IntegerField(unique=True),
        ),
    ]
