# Generated by Django 3.0.4 on 2020-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200602_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationroom',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
    ]
