# Generated by Django 3.0.4 on 2020-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20200602_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_start',
        ),
        migrations.AlterField(
            model_name='reservationroom',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
    ]
