# Generated by Django 3.0.4 on 2020-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20200602_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationroom',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='reservationroom',
            name='date_start',
        ),
        migrations.AlterField(
            model_name='reservationroom',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('New', 'New'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
    ]
